------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [1]:
import numpy as np

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

##### 1. Crea un vector entre 7 y 66.

In [7]:
a = np.arange(7,67)
a

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66])

##### 2. Invierte el vector generado anteriormente.

In [8]:
invert_a = a[::-1]
invert_a

array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

##### 3. Matriz de 4x4 con valores entre 0 y 15.

In [11]:
j = np.arange(4*4).reshape(4,4)
j

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### 5. Crea la matriz identidad de 5x5.

In [13]:
iden= np.identity(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### 6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.

In [61]:
matriz = np.zeros((5,5))
n = 0
while n <= 4:
    m = 0
    while m < 5:
        if n == 0 or n== 4 or m == 0 or m == 4:
            matriz[n,m] = 1
        elif n == m == 2:
            matriz[n,m] = 1
        m += 1
    n += 1
matriz

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### 7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.

In [108]:
m4 = np.empty((0, 4), int)
for i in range(4):
    m4 = np.append(m4,np.array([[0,1,2,3]]), axis =0)
m4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

##### 8. Crea un array de ceros de 2x7.

In [115]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

##### 9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.

In [118]:
ceros = np.zeros((5,4))
n = 0
while n < 4:
    ceros[0,n] = 1
    n += 1
ceros

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
ceros = np.zeros((5,4))
for i in range(4):
    ceros[0,i] = 1
ceros

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### 10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [134]:
tab = np.zeros((8,8))
tab

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [135]:
n = 0
while n < 8:
    m = 0
    while m < 8:
        if n %2 == 0 and m % 2 == 0:
            tab[n,m] = 1
        elif n%2 !=0 and m%2 != 0:
            tab[n,m] = 1
        m += 1
    n += 1
print(tab)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
